name: Check starter app

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run public data product checker
        run: python autograder/check_public_data_product.py starter_app
      - name: Syntax check starter app
        run: python -m py_compile starter_app/app.py
